from .persona import Persona
from .usuario import Usuario
from .red import RedEssalud
from .ipress import IpressEssalud
from .rol import Rol
from .rol_usuario import RolUsuario
from .menu import Menu
from .opcion import Opcion
from .rol_opcion import RolOpcion
from .gestor_redes import GestorRedes
from .departamento import Departamento
from .provincia import Provincia
from .distrito import Distrito
from .macroregion import Macrorregion
from .tiporeporte import TipoReporte
from .tecnica_evaluacion import TecnicaEvaluacion
from .macroproceso import Macroproceso
from .estandar import Estandar
from .criterio import Criterio
from .condicion import CondicionCriterio
from .fuente import Fuente
from .proceso import ProcesoInstitucional
from .autoevaluacion import Autoevaluacion
from .autoevaluacionreporte import AutoevaluacionReporte
from .autoevaluacionreportecriterio import AutoevaluacionReporteCriterio
from .autoevaluacionreportecomentario import AutoevaluacionReporteComentario
from .tipo_observacion import TipoObservacion
from .autoevaluacioncomentariotecnica import AutoevaluacionComentarioTecnica
from .autoevaluaciontecnicaobservacion import AutoevaluacionTecnicaObservacion
from .autoevaluacionhistorico import AutoevaluacionHistorico
from .acreditacionh1equipoacreditacion import AcreditacionH1EquipoAcreditacion
from .acreditacionreportehitos import AcreditacionReporteHitos